import type { SolarDataPoint } from '@/types/solar';

export const DEMO_DATA: SolarDataPoint[] = [
  { date: '2026-01-01', production_kwh: 373, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: true  },
  { date: '2026-01-02', production_kwh: 387, site_name: 'Clenergize Solar Site A', weather: 'Sunny',         anomaly_detected: false },
  { date: '2026-01-03', production_kwh: 393, site_name: 'Clenergize Solar Site A', weather: 'Sunny',         anomaly_detected: false },
  { date: '2026-01-04', production_kwh: 353, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: false },
  { date: '2026-01-05', production_kwh: 366, site_name: 'Clenergize Solar Site A', weather: 'Sunny',         anomaly_detected: false },
  { date: '2026-01-06', production_kwh: 348, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: false },
  { date: '2026-01-07', production_kwh: 356, site_name: 'Clenergize Solar Site A', weather: 'Partly Cloudy', anomaly_detected: false },
  { date: '2026-01-08', production_kwh: 353, site_name: 'Clenergize Solar Site A', weather: 'Partly Cloudy', anomaly_detected: false },
  { date: '2026-01-09', production_kwh: 362, site_name: 'Clenergize Solar Site A', weather: 'Sunny',         anomaly_detected: false },
  { date: '2026-01-10', production_kwh: 373, site_name: 'Clenergize Solar Site A', weather: 'Sunny',         anomaly_detected: false },
  { date: '2026-01-11', production_kwh: 365, site_name: 'Clenergize Solar Site A', weather: 'Partly Cloudy', anomaly_detected: false },
  { date: '2026-01-12', production_kwh: 354, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: false },
  { date: '2026-01-13', production_kwh: 324, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: false },
  { date: '2026-01-14', production_kwh: 334, site_name: 'Clenergize Solar Site A', weather: 'Partly Cloudy', anomaly_detected: false },
  { date: '2026-01-15', production_kwh: 294, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: false },
  { date: '2026-01-16', production_kwh: 293, site_name: 'Clenergize Solar Site A', weather: 'Partly Cloudy', anomaly_detected: false },
  { date: '2026-01-17', production_kwh: 304, site_name: 'Clenergize Solar Site A', weather: 'Sunny',         anomaly_detected: false },
  { date: '2026-01-18', production_kwh: 285, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: false },
  { date: '2026-01-19', production_kwh: 286, site_name: 'Clenergize Solar Site A', weather: 'Partly Cloudy', anomaly_detected: false },
  { date: '2026-01-20', production_kwh: 276, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: false },
  { date: '2026-01-21', production_kwh: 250, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: false },
  { date: '2026-01-22', production_kwh: 203, site_name: 'Clenergize Solar Site A', weather: 'Sunny',         anomaly_detected: true  },
  { date: '2026-01-23', production_kwh: 223, site_name: 'Clenergize Solar Site A', weather: 'Sunny',         anomaly_detected: false },
  { date: '2026-01-24', production_kwh: 198, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: false },
  { date: '2026-01-25', production_kwh: 100, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: true  },
  { date: '2026-01-26', production_kwh: 100, site_name: 'Clenergize Solar Site A', weather: 'Sunny',         anomaly_detected: true  },
  { date: '2026-01-27', production_kwh: 100, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: false },
  { date: '2026-01-28', production_kwh: 100, site_name: 'Clenergize Solar Site A', weather: 'Sunny',         anomaly_detected: true  },
  { date: '2026-01-29', production_kwh: 100, site_name: 'Clenergize Solar Site A', weather: 'Sunny',         anomaly_detected: false },
  { date: '2026-01-30', production_kwh: 100, site_name: 'Clenergize Solar Site A', weather: 'Cloudy',        anomaly_detected: true  },
];
